enum Scenes {
  PRELOAD = 'PRELOAD',
  MAINMENU = 'MAINMENU',
  GAME = 'GAME',
}

enum GameEvents {
  BOARD_GENERATED = 'BOARD_GENERATED',
  MINECOUNT_GENERATED = 'MINECOUNT_GENERATED',
  TIMER_GENERATED = 'TIMER_GENERATED',
}

export { Scenes, GameEvents };
