enum Scenes {
  PRELOAD = 'PRELOAD',
  MAINMENU = 'MAINMENU',
  GAME = 'GAME',
}

enum GameEvents {
  BOARD_GENERATED = 'BOARD_GENERATED',
  MINECOUNT_GENERATED = 'MINECOUNT_GENERATED',
  TIMER_GENERATED = 'TIMER_GENERATED',
  EMOJI_UPDATED = 'EMOJI_UPDATED',
  EMOJI_THINK = 'EMOJI_THINK',
  EMOJI_GASP = 'EMOJI_GASP',
  EMOJI_DEAD = 'EMOJI_DEAD',
  EMOJI_WIN = 'EMOJI_WIN',
  RESTART = 'RESTART',
}

export { Scenes, GameEvents };
